# Assignment 4: Data Wrangling
```
Course: ENV 700 - Environmental Data Exploration
Author: Peyton Smith
Date: Fall 2026
```

This notebook accompanies the Python lessons on **Data Wrangling**, the second stage in the data analytics pipeline: **exploration, wrangling, analysis, and visualization**.

In this notebook, you will be working with US EPA Air Quality System (AQS) data on ozone and fine particulate matter (2.5 mm) levels recorded at its North Carolina monitoring stations for the years 2024 and 2025. The raw data files are provided as four separate CSV files: one for each pollutant-year combination. In this exercise, you will import each and wrangle them separately so that they can be combined into a single dataframe, where additional wrangling will enable comprehensive analysis of the dataset.

---
### 1. Set up your Python Session

#### ✅ 1.1 Import Packages
* Load the pathlib Path object and the Pandas package into your coding environnment

In [ ]:
# 1.1 Import Packages
from pathlib import Path
import pandas as pd

#### ✅ 1.2 Set project folder variables
* Create three Path variables, one set to your project's **root folder** one set to the **raw data folder** and another to the **processed data folder**. 
* Display the the values of these three variables in your notebook.

In [ ]:
# 1.2 Set project folders using relative paths
project_fldr = Path.cwd().parent
raw_fldr = project_fldr /'assignments'/ 'data' / 'raw'
processed_fldr = project_fldr /'assignments'/ 'data' / 'processed'

PosixPath('/workspaces/ENV700/assignments/data/raw')

#### ✅ 1.3 Set a path to the raw data files
* Create a Path variable pointing to the four EPA AQS files found in the raw data folder: 
    - `EPAair_O3_NC2024_raw.csv`
    - `EPAair_O3_NC2025_raw.csv`
    - `EPAair_PM25_NC2024_raw.csv`
    - `EPAair_PM25_NC2025_raw.csv`

In [9]:
# 1.3 Create file path variables
EPA_o3_2024_file = raw_fldr / 'EPAair_O3_NC2024_raw.csv'
print("File exists:", EPA_o3_2024_file.exists())
EPA_o3_2025_file = raw_fldr / 'EPAair_O3_NC2025_raw.csv'
print("File exists:", EPA_o3_2025_file.exists())
EPA_pm25_2024_file = raw_fldr / 'EPAair_PM25_NC2024_raw.csv'
print("File exists:", EPA_pm25_2024_file.exists())
EPA_pm25_2025_file = raw_fldr / 'EPAair_PM25_NC2025_raw.csv'
print("File exists:", EPA_pm25_2025_file.exists())

File exists: True
File exists: True
File exists: True
File exists: True

#### ✅ 1.4 Read the four files into separate dataframes
(*No need to set data types, parse dates, or perform any other specialize import functions here; we will wrangle value later.*)

In [10]:
# 1.4 Read data into dataframes
EPA_o3_2024 = pd.read_csv(EPA_o3_2024_file)
EPA_o3_2025 = pd.read_csv(EPA_o3_2025_file)
EPA_pm25_2024 = pd.read_csv(EPA_pm25_2024_file)
EPA_pm25_2025 = pd.read_csv(EPA_pm25_2025_file)

#### ✅ 1.5 Report the dimensions of each dataframe
🔥***TIP***: *Each dataframe should have a different number of records.*

In [11]:
# 1.5 Report the dimensions of each dataset
print(EPA_o3_2024.shape) 
print(EPA_o3_2025.shape)
print(EPA_pm25_2024.shape)
print(EPA_pm25_2025.shape)

(9519, 21)
(9466, 21)
(9752, 22)
(10184, 22)

---
### 2. Wrangle individual datasets

#### ✅ 2.1 Update data types
* Convert the `Date` column in each dataframe so that values are datetime objects. 
* List the date range for the two Ozone dataframes.

In [14]:
# Convert the Date column to DateTime objects
EPA_o3_2024['Date'] = pd.to_datetime(EPA_o3_2024['Date'], format='%Y-%m-%d')
EPA_o3_2025['Date'] = pd.to_datetime(EPA_o3_2025['Date'], format='%Y-%m-%d')
EPA_pm25_2024['Date'] = pd.to_datetime(EPA_pm25_2024['Date'], format='%Y-%m-%d')
EPA_pm25_2025['Date'] = pd.to_datetime(EPA_pm25_2025['Date'], format='%Y-%m-%d')

# Print date ranges
print(EPA_o3_2024['Date'].min(), EPA_o3_2024['Date'].max())
print(EPA_o3_2025['Date'].min(), EPA_o3_2025['Date'].max())

2024-01-01 00:00:00 2024-12-30 00:00:00
2025-01-01 00:00:00 2025-12-31 00:00:00

#### ✅ 2.2 Eliminate unnecessary columns
* Subset each dataframe to include only the following columns:  
```'Date', 'Daily AQI Value', 'Local Site Name', 'AQS Parameter Description', 'County', 'Site Latitude', 'Site Longitude'```

In [20]:
# 2.2 Subset columns
EPA_o3_2024 = EPA_o3_2024.loc[:,['Date', 'Daily AQI Value', 'Local Site Name', 'AQS Parameter Description', 'County', 'Site Latitude', 'Site Longitude']]
EPA_o3_2025 = EPA_o3_2025.loc[:,['Date', 'Daily AQI Value', 'Local Site Name', 'AQS Parameter Description', 'County', 'Site Latitude', 'Site Longitude']]
EPA_pm25_2024= EPA_pm25_2024.loc[:,['Date', 'Daily AQI Value', 'Local Site Name', 'AQS Parameter Description', 'County', 'Site Latitude', 'Site Longitude']]
EPA_pm25_2025= EPA_pm25_2025.loc[:,['Date', 'Daily AQI Value', 'Local Site Name', 'AQS Parameter Description', 'County', 'Site Latitude', 'Site Longitude']]
print(EPA_o3_2024,EPA_o3_2025,EPA_pm25_2024,EPA_pm25_2025)

           Date  Daily AQI Value        Local Site Name  \
0    2024-03-01               26  Taylorsville Liledoun
1    2024-03-02               34  Taylorsville Liledoun
2    2024-03-03               35  Taylorsville Liledoun
3    2024-03-04               37  Taylorsville Liledoun
4    2024-03-05               42  Taylorsville Liledoun
...         ...              ...                    ...
9514 2024-09-20               61           Mt. Mitchell
9515 2024-09-21               47           Mt. Mitchell
9516 2024-09-22               46           Mt. Mitchell
9517 2024-09-23               37           Mt. Mitchell
9518 2024-09-24               37           Mt. Mitchell

     AQS Parameter Description     County  Site Latitude  Site Longitude
0                        Ozone  Alexander      35.913800      -81.191000
1                        Ozone  Alexander      35.913800      -81.191000
2                        Ozone  Alexander      35.913800      -81.191000
3                        Ozone  Alexander      35.913800      -81.191000
4                        Ozone  Alexander      35.913800      -81.191000
...                        ...        ...            ...             ...
9514                     Ozone     Yancey      35.765413      -82.264944
9515                     Ozone     Yancey      35.765413      -82.264944
9516                     Ozone     Yancey      35.765413      -82.264944
9517                     Ozone     Yancey      35.765413      -82.264944
9518                     Ozone     Yancey      35.765413      -82.264944

[9519 rows x 7 columns]            Date  Daily AQI Value        Local Site Name  \
0    2025-03-01               47  Taylorsville Liledoun
1    2025-03-02               41  Taylorsville Liledoun
2    2025-03-03               43  Taylorsville Liledoun
3    2025-03-04               42  Taylorsville Liledoun
4    2025-03-05               44  Taylorsville Liledoun
...         ...              ...                    ...
9461 2025-12-27               24       Millbrook School
9462 2025-12-28               22       Millbrook School
9463 2025-12-29               30       Millbrook School
9464 2025-12-30               27       Millbrook School
9465 2025-12-31               32       Millbrook School

     AQS Parameter Description     County  Site Latitude  Site Longitude
0                        Ozone  Alexander      35.913800      -81.191000
1                        Ozone  Alexander      35.913800      -81.191000
2                        Ozone  Alexander      35.913800      -81.191000
3                        Ozone  Alexander      35.913800      -81.191000
4                        Ozone  Alexander      35.913800      -81.191000
...                        ...        ...            ...             ...
9461                     Ozone       Wake      35.856111      -78.574167
9462                     Ozone       Wake      35.856111      -78.574167
9463                     Ozone       Wake      35.856111      -78.574167
9464                     Ozone       Wake      35.856111      -78.574167
9465                     Ozone       Wake      35.856111      -78.574167

[9466 rows x 7 columns]            Date  Daily AQI Value Local Site Name  \
0    2024-01-01               14  Linville Falls
1    2024-01-04               13  Linville Falls
2    2024-01-07                5  Linville Falls
3    2024-01-10                6  Linville Falls
4    2024-01-13               11  Linville Falls
...         ...              ...             ...
9747 2024-12-27               53      Triple Oak
9748 2024-12-28               45      Triple Oak
9749 2024-12-29               16      Triple Oak
9750 2024-12-30               13      Triple Oak
9751 2024-12-31               31      Triple Oak

                   AQS Parameter Description County  Site Latitude  \
0     Acceptable PM2.5 AQI & Speciation Mass  Avery      35.972347
1     Acceptable PM2.5 AQI & Speciation Mass  Avery      35.972347
2     Acceptable PM2.5 AQI & Speciation Mass  Avery      35.972347
3     Acceptable PM2.5 AQI & Speciation Mass  Avery      35.972347
4     Acceptable PM2.5 AQI & Speciation Mass  Avery      35.972347
...                                      ...    ...            ...
9747                PM2.5 - Local Conditions   Wake      35.865200
9748                PM2.5 - Local Conditions   Wake      35.865200
9749                PM2.5 - Local Conditions   Wake      35.865200
9750                PM2.5 - Local Conditions   Wake      35.865200
9751                PM2.5 - Local Conditions   Wake      35.865200

      Site Longitude
0         -81.933072
1         -81.933072
2         -81.933072
3         -81.933072
4         -81.933072
...              ...
9747      -78.819700
9748      -78.819700
9749      -78.819700
9750      -78.819700
9751      -78.819700

[9752 rows x 7 columns]             Date  Daily AQI Value Local Site Name  \
0     2025-01-01                4  Linville Falls
1     2025-01-04                7  Linville Falls
2     2025-01-07                8  Linville Falls
3     2025-01-10               23  Linville Falls
4     2025-01-13               28  Linville Falls
...          ...              ...             ...
10179 2025-12-27               49      Triple Oak
10180 2025-12-28               26      Triple Oak
10181 2025-12-29               29      Triple Oak
10182 2025-12-30               23      Triple Oak
10183 2025-12-31               24      Triple Oak

                    AQS Parameter Description County  Site Latitude  \
0      Acceptable PM2.5 AQI & Speciation Mass  Avery      35.972347
1      Acceptable PM2.5 AQI & Speciation Mass  Avery      35.972347
2      Acceptable PM2.5 AQI & Speciation Mass  Avery      35.972347
3      Acceptable PM2.5 AQI & Speciation Mass  Avery      35.972347
4      Acceptable PM2.5 AQI & Speciation Mass  Avery      35.972347
...                                       ...    ...            ...
10179                PM2.5 - Local Conditions   Wake      35.865200
10180                PM2.5 - Local Conditions   Wake      35.865200
10181                PM2.5 - Local Conditions   Wake      35.865200
10182                PM2.5 - Local Conditions   Wake      35.865200
10183                PM2.5 - Local Conditions   Wake      35.865200

       Site Longitude
0          -81.933072
1          -81.933072
2          -81.933072
3          -81.933072
4          -81.933072
...               ...
10179      -78.819700
10180      -78.819700
10181      -78.819700
10182      -78.819700
10183      -78.819700

[10184 rows x 7 columns]

#### ✅ 2.3 Update values
* For the PM2.5 datasets, fill all cells in the `AQS Parameter Description` with the string "PM2.5".  
(*All cell values in this column will be identical.*)

In [64]:
# 2.3 Update values
EPA_pm25_2024['AQS Parameter Description'] = 'PM2.5'
EPA_pm25_2025['AQS Parameter Description'] = 'PM2.5'
print(EPA_pm25_2024['AQS Parameter Description'],EPA_pm25_2025['AQS Parameter Description'])

0       PM2.5
1       PM2.5
2       PM2.5
3       PM2.5
4       PM2.5
        ...
9747    PM2.5
9748    PM2.5
9749    PM2.5
9750    PM2.5
9751    PM2.5
Name: AQS Parameter Description, Length: 9752, dtype: str 0        PM2.5
1        PM2.5
2        PM2.5
3        PM2.5
4        PM2.5
         ...
10179    PM2.5
10180    PM2.5
10181    PM2.5
10182    PM2.5
10183    PM2.5
Name: AQS Parameter Description, Length: 10184, dtype: str

---
### 3. Combine datasets

#### ✅ 3.1 Confirm dataframes are set to be merged
* Ensure that column names in each dataframe are indentical

In [30]:
# 3.1 Ensure column are same across all dataframes
print(EPA_o3_2024.columns)
print(EPA_o3_2025.columns)
print(EPA_pm25_2024.columns)
print(EPA_pm25_2025.columns)

Index(['Date', 'Daily AQI Value', 'Local Site Name',
       'AQS Parameter Description', 'County', 'Site Latitude',
       'Site Longitude'],
      dtype='str')
Index(['Date', 'Daily AQI Value', 'Local Site Name',
       'AQS Parameter Description', 'County', 'Site Latitude',
       'Site Longitude'],
      dtype='str')
Index(['Date', 'Daily AQI Value', 'Local Site Name',
       'AQS Parameter Description', 'County', 'Site Latitude',
       'Site Longitude'],
      dtype='str')
Index(['Date', 'Daily AQI Value', 'Local Site Name',
       'AQS Parameter Description', 'County', 'Site Latitude',
       'Site Longitude'],
      dtype='str')

#### ✅ 3.2 Combine the datasets 
* Combine the datasets using Pandas' `concat()` function
* Report the dimensions of the merged dataframe. (This should be `38,921 x 7`)

In [32]:
# 3.2 Concatentate & report shape
combined_EPA=pd.concat([EPA_o3_2024,EPA_o3_2025,EPA_pm25_2024,EPA_pm25_2025], ignore_index=True)
combined_EPA.shape

(38921, 7)

#### ✅ 3.3 Examine the contents of the merged dataframe
* Display a sample of 10 randomly selected rows, using the random state = 42

In [35]:
# 3.3 View a sample of data
combined_EPA.sample(10, random_state=42)

,Date,Daily AQI Value,Local Site Name,AQS Parameter Description,County,Site Latitude,Site Longitude
26921,2024-07-20,24,Pitt Agri. Center,PM2.5,Pitt,35.641276,-77.360126
6483,2024-04-22,40,University Meadows,Ozone,Mecklenburg,35.314158,-80.713469
34315,2025-02-18,53,Remount,PM2.5,Mecklenburg,35.213171,-80.874084
12494,2025-08-08,39,Clemmons Middle,Ozone,Forsyth,36.026612,-80.341962
27781,2024-01-08,12,Old High School,PM2.5,Swain,35.498711,-83.310242
23089,2024-08-26,59,Mendenhall School,PM2.5,Guilford,36.109006,-79.802314
35024,2025-02-16,27,Spruce Pine Hospital,PM2.5,Mitchell,35.912487,-82.062082
1157,2024-08-14,40,Beaufort,Ozone,Carteret,34.884800,-76.620300
4178,2024-09-14,31,Waynesville School,Ozone,Haywood,35.507224,-82.963625
13592,2025-03-29,45,Waynesville School,Ozone,Haywood,35.507224,-82.963625

---
### 4. Wrangle the combined dataset

#### ✅ 4.1 Subset rows 
* Generate a list of local site names common to all 4 dataframes (code provided, but replace the dataframe names to match your own).
* Create a subset of the full dataset, selecting those that match these local site names.
* Report the dimensions of the resulting dataframe. (This should be `18,778 x 7`)

In [38]:
# Generate a list of local site names common to all 4 dataframes
## Create set objects from the values in the Local Site Name columns
EPA_o3_2024_sites = set(EPA_o3_2024['Local Site Name']) #<-- update dataframe name to use your 2024 Ozone dataframe
EPA_o3_2025_sites = set(EPA_o3_2025['Local Site Name'])
EPA_pm25_2024_sites = set(EPA_pm25_2024['Local Site Name'])
EPA_pm25_2025_sites = set(EPA_pm25_2025['Local Site Name'])
## Compute the intersection 
common_sites = EPA_o3_2024_sites & EPA_o3_2025_sites & EPA_pm25_2024_sites & EPA_pm25_2025_sites
common_sites

{'Bryson City',
 'Castle Hayne',
 'Clemmons Middle',
 'Durham Armory',
 'Frying Pan Mountain',
 'Garinger High School',
 'Hattie Avenue',
 'Leggett',
 'Linville Falls',
 'Mendenhall School',
 'Millbrook School',
 'Old High School',
 'Pitt Agri. Center',
 'Rockwell',
 'West Johnston Co.'}

In [42]:
# 4.1 Subset for records with sites in common
combined_EPA_subset = combined_EPA.loc[combined_EPA['Local Site Name'].isin(common_sites)]
print(combined_EPA_subset)

            Date  Daily AQI Value   Local Site Name AQS Parameter Description  \
245   2024-03-01               31    Linville Falls                     Ozone
246   2024-03-02               37    Linville Falls                     Ozone
247   2024-03-03               38    Linville Falls                     Ozone
248   2024-03-04               36    Linville Falls                     Ozone
249   2024-03-05               43    Linville Falls                     Ozone
...          ...              ...               ...                       ...
38562 2025-12-27               52  Millbrook School                     PM2.5
38563 2025-12-28               34  Millbrook School                     PM2.5
38564 2025-12-29               32  Millbrook School                     PM2.5
38565 2025-12-30               19  Millbrook School                     PM2.5
38566 2025-12-31               24  Millbrook School                     PM2.5

      County  Site Latitude  Site Longitude
245    Avery      35.972347      -81.933072
246    Avery      35.972347      -81.933072
247    Avery      35.972347      -81.933072
248    Avery      35.972347      -81.933072
249    Avery      35.972347      -81.933072
...      ...            ...             ...
38562   Wake      35.856111      -78.574167
38563   Wake      35.856111      -78.574167
38564   Wake      35.856111      -78.574167
38565   Wake      35.856111      -78.574167
38566   Wake      35.856111      -78.574167

[18778 rows x 7 columns]

#### ✅ 4.2 Group and summarize data 
We want a dataset that lists one record per measured pollutant per location per day. To ensure we have that, we'll group data by date, local site name, AQS parameter, and county, computing the mean daily AQI value as well as mean latitude and longitude value. 
* Group the data on the grouping variables mentioned above. 
* For each group, compute mean daily AQI value, mean latitude, and mean longitude. 
* Reset the index of the summarized dataset to restore the product to a flat dataframe.
* Report the dimensions of the dataset. (This should be `17,017 x 7`.)

In [44]:
combined_EPA_subset.head()

,Date,Daily AQI Value,Local Site Name,AQS Parameter Description,County,Site Latitude,Site Longitude
245,2024-03-01,31,Linville Falls,Ozone,Avery,35.972347,-81.933072
246,2024-03-02,37,Linville Falls,Ozone,Avery,35.972347,-81.933072
247,2024-03-03,38,Linville Falls,Ozone,Avery,35.972347,-81.933072
248,2024-03-04,36,Linville Falls,Ozone,Avery,35.972347,-81.933072
249,2024-03-05,43,Linville Falls,Ozone,Avery,35.972347,-81.933072

In [55]:
# 4.2 Group and summarize data, then report its dimensions
grouped_EPA_combined = combined_EPA_subset.groupby(
    ['Date', 'Local Site Name', 'AQS Parameter Description', 'County']
).agg(
    mean_AQS=('Daily AQI Value', 'mean'),
    mean_lat=('Site Latitude', 'mean'),
    mean_long=('Site Longitude', 'mean')
).reset_index()
grouped_EPA_combined.shape

(17017, 7)

#### ✅ 4.3 Add calculated columns
* Add `Year` and `Month` columns to your dataframe, deriving values from the `Date` field.

In [56]:
# 4.3 Calculate year and month columns
grouped_EPA_combined = grouped_EPA_combined.assign(
    Year=lambda df: df["Date"].dt.year,
    Month=lambda df: df["Date"].dt.month
)
grouped_EPA_combined.head()

,Date,Local Site Name,AQS Parameter Description,County,mean_AQS,mean_lat,mean_long,Year,Month
0,2024-01-01,Bryson City,PM2.5,Swain,43.0,35.434767,-83.442133,2024,1
1,2024-01-01,Castle Hayne,PM2.5,New Hanover,44.5,34.364167,-77.838611,2024,1
2,2024-01-01,Clemmons Middle,PM2.5,Forsyth,47.5,36.026612,-80.341962,2024,1
3,2024-01-01,Durham Armory,PM2.5,Durham,61.0,36.032955,-78.904037,2024,1
4,2024-01-01,Frying Pan Mountain,PM2.5,Haywood,14.0,35.379167,-82.792500,2024,1

#### ✅ 4.4 Spread AQI values into separate columns: OZone & PM2.5
* Reshape our table so that Daily AQI values for Ozone and PM2.5 data appear in separate columns.
* Reset the index of the reshaped table to restore it as a flat dataframe.
* Display the first 5 records in the resulting dataframe

In [58]:
# 4.4 Spread data so Ozone, PM2.5 daily AQI valiues occupy separate columns
grouped_EPA_combined_wide = (
    grouped_EPA_combined
    .pivot_table(
        index=['Date', 'Local Site Name', 'County', 'Year', 'Month'],
        columns='AQS Parameter Description',
        values='mean_AQS'
    )
    .reset_index()
)

grouped_EPA_combined_wide.head()

AQS Parameter Description,Date,Local Site Name,County,Year,Month,Ozone,PM2.5
0,2024-01-01,Bryson City,Swain,2024,1,NaN,43.0
1,2024-01-01,Castle Hayne,New Hanover,2024,1,NaN,44.5
2,2024-01-01,Clemmons Middle,Forsyth,2024,1,NaN,47.5
3,2024-01-01,Durham Armory,Durham,2024,1,NaN,61.0
4,2024-01-01,Frying Pan Mountain,Haywood,2024,1,NaN,14.0

---
## 5. Save your processed dataset

#### ✅ 5.1 Save the spread dataset to a file 
* Name the spread data file `EPAair_O3_PM25_NC2425_Processed.csv`
* Save it to your processed data folder
* Do not include the dataframe index in your saved file

In [59]:
# 5.1 Save the file
grouped_EPA_combined_wide.to_csv(processed_fldr/'EPAair_data_lab4.csv',index=False)

---
## 6. Summarize and explore the data

#### ✅ 6.1 Generate a month summary table
* Group the above table to compute mean Ozone and PM2.5 values for each unique site, month, year combination. Be sure to reset the index of the product. 
* Display the first 5 records of this table.

In [63]:
# 6.1 Generate a summary table and show its first 5 records
EPA_mean_os_pm25 = (
    grouped_EPA_combined_wide
    .groupby(['Local Site Name', 'Year', 'Month'])
    .agg(
        mean_ozone=('Ozone', 'mean'),
        mean_pm25=('PM2.5', 'mean')
    )
    .reset_index()
)

EPA_mean_os_pm25.head()

  Local Site Name  Year  Month  mean_ozone  mean_pm25
0     Bryson City  2024      1         NaN  22.580645
1     Bryson City  2024      2         NaN  32.000000
2     Bryson City  2024      3   40.709677  30.935484
3     Bryson City  2024      4   43.793103  36.066667
4     Bryson City  2024      5   37.419355  30.387097

---
## 7. Submission
- Save, stage, and commit this notebook
- Push changes to your GitHub account
- Export as an HTML document
- Submit both your `.ipynb` and `.html` document to Canvas.